### ISSUE TITLE
Helpful Information

### ISSUE THREAD

**Issue by CodingSamurai** [janaks09/dotnetcoresamples#1]
For anyone else that ends up here a couple of helpful notes:

In FileOperation on line 5 the operation.OperationID.ToLower() needs to be the following format:

[url prefix][controllername][urlparams][httpmethod]

so this Route HTTPPost('api/Documents/{docid}') becomes 'apidocumentsbydocidpost'

Also if you need to add a parameters from the URL the NonBodyParameter.In should be set to 'path'.

Hope that helps other people!

**Comment by janaks09** [comment]
Thanks @CodingSamurai
